# Generated by Django 5.0.6 on 2025-03-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(upload_to='photos/ProjectPhoto')),
                ('campaign_start_date', models.DateField()),
                ('campaign_end_date', models.DateField()),
                ('minimum_investment', models.FloatField()),
                ('maximum_investment', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('funded', 'Funded')], default='active', max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.register')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.projectdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.register')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.projectdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.register')),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=50)),
                ('creation_date', models.DateField()),
                ('phone', models.BigIntegerField()),
                ('website_url', models.URLField(max_length=100)),
                ('startup_email', models.EmailField(max_length=254, unique=True)),
                ('amount_to_raise', models.FloatField()),
                ('equity_offer', models.FloatField()),
                ('funding_goal', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.category')),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.register')),
            ],
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='startup_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.startup'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_statements', models.FileField(max_length=200, upload_to='startup_documents/financial_statements')),
                ('business_plan', models.FileField(max_length=200, upload_to='startup_documents/business_plan')),
                ('pitch_deck', models.FileField(max_length=200, upload_to='startup_documents/pitch_deck')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.register')),
                ('startup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.startup')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('update_date', models.DateField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=30)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.projectdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.register')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/UserPhoto')),
                ('linkedin_url', models.URLField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField()),
                ('aadhar_card', models.ImageField(help_text='Upload a clear image of your Aadhar card', upload_to='photos/AadharCardPhoto')),
                ('role', models.CharField(choices=[('entrepreneur', 'Entrepreneur'), ('investor', 'Investor')], max_length=15)),
                ('experience', models.TextField()),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.register')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.projectdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.register')),
            ],
        ),
    ]
