# Generated by Django 5.0.6 on 2025-03-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_userdetails_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='status',
        ),
    ]
