# Generated by Django 5.0.6 on 2025-03-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_remove_userdetails_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='status',
        ),
    ]
