# Generated by Django 5.0.6 on 2025-03-07 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
