# Generated by Django 5.0.6 on 2025-03-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0008_startup_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
