# Generated by Django 5.0.6 on 2025-03-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0011_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('released_to_entrepreneur', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('admin_verified', models.BooleanField(default=False)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pancard', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('equity_offered', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('track_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending in Escrow'), ('released', 'Released to Entrepreneur'), ('refunded', 'Refunded to Investor'), ('failed', 'Payment Failed')], default='pending', max_length=20)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('funds_released_date', models.DateTimeField(blank=True, null=True)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.projectdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.register')),
            ],
        ),
        migrations.CreateModel(
            name='EquityDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('equity_percentage', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('startup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.startup')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.register')),
                ('investment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro.investment')),
            ],
        ),
    ]
