# Generated by Django 5.0.6 on 2025-04-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0012_escrowrelease_investment_equitydistribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='track_id',
        ),
    ]
