# Generated by Django 5.0.6 on 2025-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0013_remove_investment_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrowrelease',
            name='project_id',
        ),
        migrations.AddField(
            model_name='investment',
            name='fund_total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EquityDistribution',
        ),
        migrations.DeleteModel(
            name='EscrowRelease',
        ),
    ]
